a = input('Digite algo:')
print ('O tipo desse valor é',type(a))
print ('É so espaco?', a.isspace())
print ('É um numero?', a.isnumeric())
print ('É um alfabetico?', a.isalpha())
print ('É alfanumerico?', a.isalnum())
print ('Esta em maiuscula?', a.isupper())
print ('Esta em minuscula?', a.islower())
print ('Esta captalizada?', a.istitle())
